# roles/git/tasks/update.yml

- name: Update messaging service
  shell: npm update
  args:
    chdir: "../services/messaging"
  ignore_errors: yes

- name: Git commit and push for messaging service
  shell: |
    git add package-lock.json
    git commit -m "chore: update package to latest"
    git push
  args:
    chdir: "../services/messaging"

- name: Update data collection service
  shell: npm update
  args:
    chdir: "../services/data-collection-service"
  ignore_errors: yes

- name: Git commit and push for data collection service
  shell: |
    git add package-lock.json
    git commit -m "chore: update package to latest"
    git push
  args:
    chdir: "../services/data-collection-service"

- name: Update data processing hub service
  shell: npm update
  args:
    chdir: "../services/data-processing-hub"
  ignore_errors: yes

- name: Git commit and push for data processing hub service
  shell: |
    git add package-lock.json
    git commit -m "chore: update package to latest"
    git push
  args:
    chdir: "../services/data-processing-hub"

- name: Update job scheduler service
  shell: npm update
  args:
    chdir: "../services/job-scheduler-service"
  ignore_errors: yes

- name: Git commit and push for job scheduler service
  shell: |
    git add package-lock.json
    git commit -m "chore: update package to latest"
    git push
  args:
    chdir: "../services/job-scheduler-service"
