- name: Ensure git submodules are initialized and updated
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.path }}"
    version: main
    update: yes
    recursive: yes
  loop:
    - { path: "../services/fetcher", url: "https://github.com/AutoContentLabs/fetcher.git" }
    - { path: "../services/messaging-utils", url: "https://github.com/AutoContentLabs/messaging-utils.git" }
    - { path: "../services/messaging", url: "https://github.com/AutoContentLabs/messaging.git" }
    - { path: "../services/databases", url: "https://github.com/AutoContentLabs/databases.git" }
    - { path: "../services/workflow-manager", url: "https://github.com/AutoContentLabs/workflow-manager.git" }
    - { path: "../services/data-collection-service", url: "https://github.com/AutoContentLabs/data-collection-service.git" }
    - { path: "../services/data-processing-hub", url: "https://github.com/AutoContentLabs/data-processing-hub.git" }
    - { path: "../services/job-scheduler-service", url: "https://github.com/AutoContentLabs/job-scheduler-service.git" }

- name: Update git submodules recursively
  command: git submodule update --remote --recursive
  args:
    chdir: "{{ playbook_dir }}"
  register: git_submodules_updated
  ignore_errors: yes

- name: Check if git submodules update was successful
  debug:
    msg: "Git submodules were successfully updated."
  when: git_submodules_updated.rc == 0

- name: Print git submodule update failure message
  debug:
    msg: "Git submodules update failed."
  when: git_submodules_updated.rc != 0
