# roles/docker/tasks/clean.yml

- name: Gather list of running containers
  command: docker ps -q
  register: docker_ps_q

- name: Gather list of all containers
  command: docker ps -a -q
  register: docker_ps_a_q

- name: Gather list of dangling images
  command: docker images -q --filter "dangling=true"
  register: docker_images_q

- name: Gather list of all volumes
  command: docker volume ls -q
  register: docker_volumes 

- name: Stop all running containers
  shell: docker stop $(docker ps -q)
  when: docker_ps_q.stdout != ''
  ignore_errors: yes

- name: Remove all containers
  shell: docker rm $(docker ps -a -q)
  when: docker_ps_a_q.stdout != ''
  ignore_errors: yes

- name: Remove unused volumes
  command: docker volume prune -f

- name: Remove unused volumes
  command: docker volume rm {{ item }}
  loop: "{{ docker_volumes.stdout_lines }}"
  when: docker_volumes.stdout != ''
  ignore_errors: yes

- name: Remove unused images
  shell: docker rmi $(docker images -q --filter "dangling=true")
  when: docker_images_q.stdout != ''
  ignore_errors: yes

- name: Remove unused networks
  command: docker network prune -f
  ignore_errors: yes

- name: Print cleanup completion message
  debug:
    msg: "All containers, volumes, images, and networks have been successfully removed."

