# playbook.yml

- name: Clean up Docker and Start Services
  hosts: localhost
  become: true
  tasks:
    - name: Update git module and package
      include_tasks: roles/git/tasks/update.yml

    - name: Clean up Docker environment
      include_tasks: roles/docker/tasks/clean.yml

    - name: Start all necessary services
      include_tasks: roles/docker/tasks/start.yml
